### PR TITLE
Set (optional) secret to secure webhook

### PR DESCRIPTION
**Pull request by smoll**
I added an option for securing the webhook based on [GitHub's suggested approach](https://developer.github.com/webhooks/securing/) and this [node implementation](https://github.com/rvagg/github-webhook-handler) & updated the README.

Please let me know if there's anything I can do to improve this, I am new to nodejs but always willing to learn more. I have tested this out with a PR-commenter I scripted and it appears to work exactly as expected. I was even able to test the negative case by manually updating the webhook after it was auto-generated with a different password, and the node server correctly rejected the next POST from GitHub.

### CODE REVIEW

**Comment by totten** [comment]
+1. Also works for me. Thank you, @smoll. (And thank you to the original authors, too!)

**Comment by masylum** [comment]
:+1:

**Comment by fcsonline** [comment]
:+1:

**Comment by mllocs** [comment]
:+1:

**Pull request merged**
